sudo: required
dist: trusty
language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - npm install -g codecov
  - npm install
script:
  - npm run build
  - npm test -- --coverage
  - codecov
notifications:
  email: false
